### ISSUE TITLE
stolen?

### ISSUE THREAD

**Issue by Vukky123** [BinaryBytes01/Skribbl.io-Plus#1]
This script seems to be stolen from https://github.com/Sv443/skribbl.io-plus with no credit to the original owner.

**Comment by BinaryBytes01** [comment]
> this script seems to be stolen from https://github.com/Sv443/skribbl.io-plus with no credit to the original owner

I did Take it from https://github.com/Sv443/skribbl.io-plus, But I did modify it, added my own features. The Original repo has a license wich says 

Permissions
 Commercial use
 Modification
 Distribution
 Private use

**Comment by Vukky123** [comment]
The license also says that the original copyright owner's copyright notice and license notice should be kept in, not removed.

**Comment by Vukky123** [comment]
You have not resolved this issue. Although I am not a lawyer, something more like this would be preferred:

Based on [skribbl.io+](https://github.com/Sv443/skribbl.io-plus) [(license)](https://raw.githubusercontent.com/Sv443/skribbl.io-plus/master/LICENSE) by Sv443.

**Comment by ProFireDev** [comment]
love the stolen script lol @Vukky123 was the original author, at the very least you need to credit him. but even with that you are not following the license properly
